name: First Interaction

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest

    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue! We appreciate your contribution."
        pr-message: "Thank you for submitting your first pull request! We appreciate your contribution."
